### ISSUE TITLE
The userdata-directory "plugin.video.vk" is not created on first start

### ISSUE THREAD

**Issue by ostvanc** [tommistolercz/plugin.video.vk#109]
On Linux, the user data for the addons is saved in ~/.kodi/userdata/addon_data. This addon uses the file saved in ~/.kodi/userdata/addon_data/plugin.video.vk/db.json, but does not check on first start if the directory plugin.video.vk exists. This leads to the following bug:

2022-08-09 19:49:53.338 T:6791  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2022-08-09 19:49:53.339 T:6791    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'FileNotFoundError'>
                                                   Error Contents: [Errno 2] No such file or directory: '/home/ostvanc/.kodi/userdata/addon_data/plugin.video.vk/db.json'
                                                   Traceback (most recent call last):
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 1846, in <module>
                                                       dispatch()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 278, in dispatch
                                                       handler(**urlargs)
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 290, in listaddonmenu
                                                       db = tinydb.TinyDB(buildfp(FILENAME_DB))
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 160, in __init__
                                                       self._storage = storage(*args, **kwargs)
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/tinydb/storages.py", line 93, in __init__
                                                       touch(path, create_dirs=create_dirs)  # Create file if not exists
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/tinydb/storages.py", line 28, in touch
                                                       with open(fname, 'a'):
                                                   FileNotFoundError: [Errno 2] No such file or directory: '/home/ostvanc/.kodi/userdata/addon_data/plugin.video.vk/db.json'
                                                   -->End of Python script error report<--

This bug does not only appear on Linux, but also on other systems like Windows and Android TV. Unless you do not have root access, you are not able to create the missing directory manually on ATV.

**Comment by tommistolercz** [comment]
Thanks for posting this issue, but I'm confused a bit ;-)

Under what circumstances do you run the addon without existing addon data folder? (~/.kodi/userdata/addon_data/plugin.video.vk/)

This folder is created automatically by Kodi, typically when the addon settings are saved for the first time. If this folder doesn't exist, there isn't even a settings.xml with VK credentials, and thus the addon can't be run at all.

**Comment by ostvanc** [comment]
Oh yes, you are right. There is only one way to run this addon without existing addon data directory:

Install the VK addon and run it directly. Then the directory ~/.kodi/userdata/addon_data/plugin.video.vk/ does not exists yet and this error occurs. 

If you open addon settings first and save your changes, then this directory is created automatically and this error does not appear anymore.

**Comment by ostvanc** [comment]
I think, this issue can be closed now.
