### ISSUE TITLE
Captcha needed

### ISSUE THREAD

**Issue by ostvanc** [tommistolercz/plugin.video.vk#110]
After setting my VK login and VK password, I cannot proceed in this addon because of this error.

2022-08-09 21:12:30.710 T:14137   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'vk_api.exceptions.Captcha'>
                                                   Error Contents: Captcha needed
                                                   Traceback (most recent call last):
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 1846, in <module>
                                                       dispatch()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 278, in dispatch
                                                       handler(**urlargs)
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 296, in listaddonmenu
                                                       vkapi = initvkapi()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 173, in initvkapi
                                                       vkauthsession = initvkauthsession()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 161, in initvkauthsession
                                                       vkauthsession.auth()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/vk_api/vk_api.py", line 187, in auth
                                                       self._auth_cookies(reauth=reauth)
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/vk_api/vk_api.py", line 207, in _auth_cookies
                                                       self._vk_login()
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/vk_api/vk_api.py", line 312, in _vk_login
                                                       return self.error_handlers[CAPTCHA_ERROR_CODE](captcha)
                                                     File "/home/ostvanc/.kodi/addons/plugin.video.vk/resources/lib/vk_api/vk_api.py", line 573, in captcha_handler
                                                       raise captcha
                                                   vk_api.exceptions.Captcha: Captcha needed
                                                   -->End of Python script error report<--

It seems that I have to solve a captcha. How can I bypass this?

**Comment by tommistolercz** [comment]
Unfortunately, the add-on currently does not support captcha during VK authorization.

Workaround:
Try logging into VK.com in a browser (use the guest mode to invoke a new login and solve the captcha there). Then run the addon again, the captcha should no longer be required.
