### ISSUE TITLE
Can't start plugin

### ISSUE THREAD

**Issue by zanozik** [tommistolercz/plugin.video.vk#99]
Fresh install on Android TX9 PRo TV Box (Android 7.1.2)
Kodi v.18.4

Plugin's settings are set.

Throws exception on startup:
````
2019-11-17 17:15:02.379 T:23969   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 1893, in <module>
                                                dispatch()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 318, in dispatch
                                                handler(**urlargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 330, in listaddonmenu
                                                db = tinydb.TinyDB(buildfp(FILENAME_DB))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 167, in __init__
                                                self._table = self.table(default_table)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 197, in table
                                                table = table_class(self._cls_storage_proxy(self._storage, name), name, **options)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 294, in __init__
                                                data = self._read()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 401, in _read
                                                return self._storage.read()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 92, in read
                                                raw_data = self._storage.read() or {}
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/storages.py", line 110, in read
                                                return json.load(self._handle)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/__init__.py", line 291, in load
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
````

`db.json` file is empty

When I set the content to a empty JSON object `{}` and start again, it will create `{"_default": {}}` object in `db.json`, and witll throw another exception:
````
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IOError'>
                                            Error Contents: [Errno 22] Invalid argument
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 1893, in <module>
                                                dispatch()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 318, in dispatch
                                                handler(**urlargs)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/addon.py", line 330, in listaddonmenu
                                                db = tinydb.TinyDB(buildfp(FILENAME_DB))
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 167, in __init__
                                                self._table = self.table(default_table)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 197, in table
                                                table = table_class(self._cls_storage_proxy(self._storage, name), name, **options)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 294, in __init__
                                                data = self._read()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 401, in _read
                                                return self._storage.read()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/database.py", line 98, in read
                                                self._storage.write(raw_data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vk/resources/lib/tinydb/storages.py", line 118, in write
                                                self._handle.truncate()
                                            IOError: [Errno 22] Invalid argument
                                            -->End of Python script error report<--
````

**Comment by zanozik** [comment]
OK, plugin suddenly started to work. I can log in, view the galleries, but when I start the video I get 
`Video resolving error."

**Comment by zanozik** [comment]
Android 7.1.2 (kernel 3.14.29)
Latest Kodi: 18.8
Latest plugin.video.vk: 17.0 Final

Bug with empty db.json - still exists
Video resolve not fixed (even though it's said fixed on the v.17 release notes).

Exceptions are the same... If you need any info or help in debugging the problem - please, let me know.

**Comment by tommistolercz** [comment]
Please try these simple steps:
- update addon to the newest version (v1.8.0)
- go to addon settings > USER tab > click LOGOUT USER button
- close settings with OK(!), restart Kodi
- run the addon and re-login with your VK credentials
